name: Test
on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get NODE_VERSION from package.json
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(node -pe node -pe "require('./package.json').engines.node")

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: Install packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Setting database
        run: docker-compose up -d
      - name: Running tests
        run: npm run test
    env:
      DATABASE_URL: postgres://admin:admin@localhost:5433/testdb
      PORT: 7778
      NODE_ENV: development
      ERROR_SHOW_EXTENSIONS: 'false'
      JWT_SECRET: secret
      JWT_EXPIRATION: 1h
      JWT_REMEMBER_ME_EXPIRATION: 12h
